name: graduation_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  chat_bubbles: ^1.6.0
  curved_labeled_navigation_bar: ^2.0.2
  dio: ^5.4.1
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/

  fonts:
    - family: myfont1
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf

    - family: myfont2
      fonts:
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf

    - family: myfont3
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf

    - family: myfont4
      fonts:
        - asset: assets/fonts/AoboshiOne-Regular.ttf

    - family: myfont5
      fonts:
        - asset: assets/fonts/BakbakOne-Regular.ttf

    - family: myfont6
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf

    - family: myfont7
      fonts:
        - asset: assets/fonts/Inika-Regular.ttf

    - family: myfont8
      fonts:
        - asset: assets/fonts/Alatsi-Regular.ttf

    - family: myfont9
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf

    - family: myfont10
      fonts:
        - asset: assets/fonts/KumarOne-Regular.ttf

# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo1.png
  # branding: assets/branding-development.png
  # color_dark: "#fff"
  # image_dark: assets/logo-development.png
  # branding_dark: assets/branding-development.png

  android_12:
    image: assets/images/logo1.png
    icon_background_color: "#ffffff"
    # image_dark: assets/logo-development.png
    # icon_background_color_dark: "#fff"

  web: false
